### ISSUE TITLE
Topic name passed as a parameter - problem

### ISSUE THREAD

**Issue by michalkrejci1** [clausdenk/MqttLogger#1]
Hello,
 Whenever I use a construct with a fixed topic name, as in the examples, i.e. MqttLogger mqttLogger(client, "mqttlogger/log");

everything is fine, but if I use a dynamic name in a char array e.g. 

char top[20];
I create an object definition
MqttLogger* mqttLog;
then I fill the top parameter e.g. from eeprom with the value "/test/topic"
and then, in setup a custom instance of the object
  mqttLog = new MqttLogger(MQTTclient,top,MqttLoggerMode::MqttAndSerial);

The mqttLog created in this way takes the last used topic from MqttPubSub when used and can be "fixed" by using only the static definition
mqttLog = new MqttLogger MQTTclient,"/test/topic",MqttLoggerMode::MqttAndSerial); 

Then everything works.

**Comment by androbi-com** [comment]
Can you provide a complete code example where we can see how "top" is set (do you use strcpy?) and then used in MqttLogger? "top" must point to a memory area in your program and be 0-terminated.

**Comment by michalkrejci1** [comment]
Hello and thank you for your prompt reply.

Below is a sample code when the problem can be triggered. Comment out the statically defined topic on the first line and try the second option.
The resulting publication is to the "last" published topic versus the correct topic.
 
 mqttLog = new MqttLogger(MQTTclient,"/module002/log",MqttLoggerMode::MqttAndSerial);

vs not working, runtime defined topic

mqttLog = new MqttLogger(MQTTclient,top,MqttLoggerMode::MqttAndSerial);

Thank you very much, M. Krejci


--------------------------------------------------------------------------------------------------------------------------------


#include <SPI.h>
#include <Ethernet.h>
#include <PubSubClient.h>
#include <MqttLogger.h>

unsigned int deviceid;
char top[40];
byte mac[] = {0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED};
IPAddress ip(192, 168, 200, 119);
IPAddress server(192,168, 200,21);

EthernetClient ethClient;
PubSubClient MQTTclient(ethClient);

MqttLogger* mqttLog;




void setup() {
 deviceid=152;

Serial.begin(115200);
 while (!Serial) {; }


Serial.print(F("\nEthernet init..."));
Ethernet.begin(mac, ip);
delay(500); // Allow the hardware to sort itself out
  Serial.println(F("done"));

 MQTTclient.setCallback(callback);
 MQTTclient.setServer(server, 1883);


 memset(top, 0, sizeof(top)); // clear id array
 sprintf_P(top, (PGM_P)F("/module%03d/log"), deviceid);
 Serial.print(F("\nPublish console messages: ")); Serial.println(top); 
 
 mqttLog = new MqttLogger (MQTTclient,"/module002/log",MqttLoggerMode::MqttAndSerial);
 //mqttLog = new MqttLogger (MQTTclient,top,MqttLoggerMode::MqttAndSerial);
}


void loop()
{
  if (!MQTTclient.connected()) {
    reconnect();
  }
  MQTTclient.loop();

   Serial.println("\nsend test2");
  MQTTclient.publish("outTopic","test2");


  sprintf_P(top, (PGM_P)F("/module%03d/R0"), deviceid);
  MQTTclient.publish(top,"0");

  mqttLog->print(F("log: "));
  mqttLog->println(millis());

  sprintf_P(top, (PGM_P)F("/module%03d/R1"), deviceid);
  MQTTclient.publish(top,"1");

  delay(2000);
}



void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i=0;i<length;i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();
}


void reconnect() {
  // Loop until we're reconnected
  while (!MQTTclient.connected()) {
    Serial.print("Attempting MQTT connection...");
     if (MQTTclient.connect("arduinoClient")) {
      Serial.println("connected");
        MQTTclient.publish("outTopic","hello world");
        MQTTclient.subscribe("inTopic");
    } else {
      Serial.print("failed, rc=");
      Serial.print(MQTTclient.state());
      Serial.println(" try again in 5 seconds");
      delay(5000);
    }
  }
}

**Comment by androbi-com** [comment]
I have no PC to check now, but this code should `mqttLog` to "/module[deviceId]/R0", right? Have in mind that MqttLogger does not buffer the string (it would use ram) that you pass in `top`. You tell MqttLogger to log to whatever `top` contains. And when you sprintf to `top` in your loop, the topic used by mqttLog changes (same pointer, different content). If you want to log to  "/module002/log" and publish to different topics, you will need to define two string buffers for your topics, say `top` and `toplog`, set `toplog` to "/module002/log" and later only change `top` in your loop.
I don't think this is an issue with MqttLogger.

**Comment by michalkrejci1** [comment]
Thanks for the reply, but I have a feeling that MqttLogger is not behaving correctly.

As you write, it should publish /module[deviceId]/R0 but it doesn't at all, it should still publish /module%03d/log no matter how the "top" data is further changed

memset(top, 0, sizeof(top)); // clear id array
 sprintf_P(top, (PGM_P)F("/module%03d/log"), deviceid)

If it is initialized statically, i.e. mqttLog = new MqttLogger(MQTTclient,"/module002/log",MqttLoggerMode::MqttAndSerial);

Then correctly and ALWAYS logs to the topic "/module002/log"

But if it is initialized from a variable, i.e. it is referenced to the char array "top"
mqttLog = new MqttLogger(MQTTclient,top,MqttLoggerMode::MqttAndSerial);

Then this object should have its own buffer corresponding to the length of the char array, and it must remember the same value throughout the lifetime of this object, just like when it is initialized statically.

Otherwise, the mqttLog->print function would also have to have a definition of the topico to publish to, even though it's mostly the same, but the object must not take the current pointer to an ever-changing topic, since a PubSub object can dynamically handle many different topics and publish many different values.

This can be solved by another, auxiliary char array variable, as you write, but that doesn't seem to me to be an optimal solution due to the initialization of the object description.

Moreover, the library defines topic as private
 private:
   const char* topic;

So it is not intended to be changed, only by the data on the pointer.
Moreover, with this notation, topic stays in allocated RAM anyway and thus saves nothing
mqttLog = new MqttLogger(MQTTclient,"/module002/log",MqttLoggerMode::MqttAndSerial);

How do you see it ?

**Comment by androbi-com** [comment]
I think this is a design choice for the library and not an issue. If you would want to implement the behavior you seem to prefer (which I would also prefer for code on a PC with no memory restrictions), the MqttLogger would need to make a local copy of the topic contents so that you can reuse your topic buffer after calling the constructor. This either requires dynamic memory allocation for the topic string or reserving an additional buffer for the topic name inside the library. The first can fail which you don't want in a logger, the second is not optimal (in general topic names can be quite long, so the buffer would have to be long enough).

So the design choice in this case is to use topic as a pointer, with all its consecuences. This leaves memory management on the callers side (you could simply allocate some memory for the topic and pass this pointer to the constructor), and has advantages and disadvantages. Care has to be taken about not reusing the pointer for other tasks as you did. In the most frequent use case where topic is a static variable it spares you precious ram, as no internal copy is needed. I admit this is not a clean object style, but ram is more important than style in some cases ;)

I will add an explanation to the docs, so it is clear for the users of the library, thanks for pointing this out as it can lead to confusion if not clearly indicated! Closing this issue.
