### ISSUE TITLE
Update PlatformIO registry with 0.2.3

### ISSUE THREAD

**Issue by sumnerboy12** [clausdenk/MqttLogger#3]
Hi - I am using PIO for my projects and the registry is stuck on 0.2.2 for [MqttLogger](https://registry.platformio.org/libraries/androbi/MqttLogger). I think maybe you need to manually push the update to 0.2.3? I am no expert tho, only started using PIO a few weeks ago...

The Arduino library has updated - see [here](https://www.arduino.cc/reference/en/libraries/mqttlogger/).

**Comment by androbi-com** [comment]
I'll have a look at it, thanx for reporting!

**Comment by sumnerboy12** [comment]
Anything I can do to help with this one? My PlatformIO build is currently failing, unless I point to the raw Github repo. Would prefer to use the PIO library registry. Sorry to be pushy! :)

**Comment by androbi-com** [comment]
I am sorry, I am quite busy with my daily job currently. I'll have to find time to look into this one, please use the raw github in the meantime.

**Comment by sumnerboy12** [comment]
No problem at all, sorry for being pushy!

**Comment by androbi-com** [comment]
It should be published now, please give it a try.

**Comment by sumnerboy12** [comment]
Thank you very much - I can confirm it is updated!
